/**
 * Configuration du showreel AMAVYA — 6 actes × 10s = 60s exact.
 * Le dernier acte (CTA) reste affiché jusqu'à action utilisateur.
 */
export const SHOWREEL_SCENES = [
  { id: "genesis", durationMs: 10000 },
  { id: "cosmos", durationMs: 10000 },
  { id: "solutions", durationMs: 10000 },
  { id: "agent", durationMs: 10000 },
  { id: "world", durationMs: 10000 },
  { id: "cta", durationMs: Infinity },
];

export const SHOWREEL_TOTAL_MS = 60000;

export const SHOWREEL_TEXT = {
  fr: {
    pageTitle: "AMAVYA — Showreel 60s",
    pageDescription: "Un voyage cinématique dans l'intelligence artificielle AMAVYA.",
    timerLabel: "TIMER",
    sceneLabels: {
      genesis: "01 · GENESIS",
      cosmos: "02 · COSMOS",
      solutions: "03 · SOLUTIONS",
      agent: "04 · L'AGENT",
      world: "05 · LE MONDE",
      cta: "06 · L'INVITATION",
    },
    close: "Quitter",
    replay: "Rejouer",
    skip: "Suivant",
    play: "Lecture",
    pause: "Pause",
    mute: "Couper le son",
    unmute: "Activer le son",
    // Textes par acte
    act1: {
      pre: "AMAVYA présente",
      brand: "AMAVYA",
      tagline: "Quand l'IA travaille pour vous",
    },
    act2: {
      pre: "Une vision",
      title: "pour le monde",
    },
    act3: {
      pre: "Notre stack",
      solutions: [
        "Agents IA autonomes",
        "CRM intelligent",
        "Automatisation métier",
        "Prospection IA",
        "SaaS sur mesure",
        "Formation IA",
      ],
      cta: "Six solutions. Une mission.",
    },
    act4: {
      pre: "L'agent qui parle",
      dialogue: [
        "Bonjour. Je suis AMAVYA.",
        "J'écoute. Je qualifie.",
        "Je vous oriente.",
      ],
    },
    act5: {
      pre: "Sur tous les continents",
      title: "Le monde parle.",
      title2: "AMAVYA écoute.",
      ticker: [
        "Le Monde · FR",
        "CNBC · US",
        "Le Devoir · CA",
        "El País · ES",
        "Corriere · IT",
        "TIME · UK",
        "РИА · RU",
        "人民日报 · CN",
        "Asahi · JP",
        "الأهرام · EG",
        "The Hindu · IN",
        "Bangkok Post · TH",
        "SMH · AU",
        "Infobae · MX",
        "CEPAL · CL",
        "CNN Esp. · BR",
        "iAfrica · ZA",
        "Tech In Africa · KE",
      ],
    },
    act6: {
      brand: "AMAVYA",
      tagline: "Prêt à transformer votre entreprise ?",
      cta: "Réserver une démo",
      footer: "amavya.cloud",
    },
  },
  en: {
    pageTitle: "AMAVYA — 60s Showreel",
    pageDescription: "A cinematic journey into AMAVYA's artificial intelligence.",
    timerLabel: "TIMER",
    sceneLabels: {
      genesis: "01 · GENESIS",
      cosmos: "02 · COSMOS",
      solutions: "03 · SOLUTIONS",
      agent: "04 · THE AGENT",
      world: "05 · THE WORLD",
      cta: "06 · THE INVITATION",
    },
    close: "Close",
    replay: "Replay",
    skip: "Skip",
    play: "Play",
    pause: "Pause",
    mute: "Mute",
    unmute: "Unmute",
    act1: {
      pre: "AMAVYA presents",
      brand: "AMAVYA",
      tagline: "When AI works for you",
    },
    act2: {
      pre: "A vision",
      title: "for the world",
    },
    act3: {
      pre: "Our stack",
      solutions: [
        "Autonomous AI Agents",
        "Intelligent CRM",
        "Business Automation",
        "AI Prospecting",
        "Custom SaaS",
        "AI Training",
      ],
      cta: "Six solutions. One mission.",
    },
    act4: {
      pre: "An agent that speaks",
      dialogue: [
        "Hello. I am AMAVYA.",
        "I listen. I qualify.",
        "I guide you forward.",
      ],
    },
    act5: {
      pre: "Across every continent",
      title: "The world speaks.",
      title2: "AMAVYA listens.",
      ticker: [
        "Le Monde · FR",
        "CNBC · US",
        "Le Devoir · CA",
        "El País · ES",
        "Corriere · IT",
        "TIME · UK",
        "РИА · RU",
        "人民日报 · CN",
        "Asahi · JP",
        "الأهرام · EG",
        "The Hindu · IN",
        "Bangkok Post · TH",
        "SMH · AU",
        "Infobae · MX",
        "CEPAL · CL",
        "CNN Esp. · BR",
        "iAfrica · ZA",
        "Tech In Africa · KE",
      ],
    },
    act6: {
      brand: "AMAVYA",
      tagline: "Ready to transform your business?",
      cta: "Book a demo",
      footer: "amavya.cloud",
    },
  },
  es: {
    pageTitle: "AMAVYA — Showreel 60s",
    pageDescription: "Un viaje cinematográfico a la inteligencia artificial AMAVYA.",
    timerLabel: "TIMER",
    sceneLabels: {
      genesis: "01 · GÉNESIS",
      cosmos: "02 · COSMOS",
      solutions: "03 · SOLUCIONES",
      agent: "04 · EL AGENTE",
      world: "05 · EL MUNDO",
      cta: "06 · LA INVITACIÓN",
    },
    close: "Cerrar",
    replay: "Reproducir",
    skip: "Saltar",
    play: "Reproducir",
    pause: "Pausa",
    mute: "Silenciar",
    unmute: "Activar sonido",
    act1: {
      pre: "AMAVYA presenta",
      brand: "AMAVYA",
      tagline: "Cuando la IA trabaja para usted",
    },
    act2: {
      pre: "Una visión",
      title: "para el mundo",
    },
    act3: {
      pre: "Nuestro stack",
      solutions: [
        "Agentes IA autónomos",
        "CRM inteligente",
        "Automatización empresarial",
        "Prospección IA",
        "SaaS a medida",
        "Formación IA",
      ],
      cta: "Seis soluciones. Una misión.",
    },
    act4: {
      pre: "Un agente que habla",
      dialogue: [
        "Hola. Soy AMAVYA.",
        "Escucho. Califico.",
        "Le oriento.",
      ],
    },
    act5: {
      pre: "En todos los continentes",
      title: "El mundo habla.",
      title2: "AMAVYA escucha.",
      ticker: [
        "Le Monde · FR",
        "CNBC · US",
        "Le Devoir · CA",
        "El País · ES",
        "Corriere · IT",
        "TIME · UK",
        "РИА · RU",
        "人民日报 · CN",
        "Asahi · JP",
        "الأهرام · EG",
        "The Hindu · IN",
        "Bangkok Post · TH",
        "SMH · AU",
        "Infobae · MX",
        "CEPAL · CL",
        "CNN Esp. · BR",
        "iAfrica · ZA",
        "Tech In Africa · KE",
      ],
    },
    act6: {
      brand: "AMAVYA",
      tagline: "¿Listo para transformar su empresa?",
      cta: "Reservar una demo",
      footer: "amavya.cloud",
    },
  },
};
