/**
 * Configuration de la page /vision — 7 scènes narratives.
 * Scène 7 (FINALE) reste affichée jusqu'à action utilisateur.
 */
export const VISION_SCENES = [
  { id: "overwhelmed", durationMs: 8000 },
  { id: "arrival", durationMs: 8000 },
  { id: "command", durationMs: 8000 },
  { id: "agents", durationMs: 12000 },
  { id: "orchestration", durationMs: 10000 },
  { id: "global", durationMs: 8000 },
  { id: "finale", durationMs: Infinity },
];

export const VISION_TOTAL_MS = 62000;

export const VISION_TEXT = {
  fr: {
    pageTitle: "AMAVYA — Vision 2035",
    pageDescription: "Un voyage cinématique dans le futur que construit AMAVYA.",
    close: "Quitter",
    replay: "Rejouer",
    skip: "Suivant",
    play: "Lecture",
    pause: "Pause",
    mute: "Couper le son",
    unmute: "Activer le son",
    sceneLabels: {
      overwhelmed: "01 · LE MONDE DÉBORDÉ",
      arrival: "02 · L'ARRIVÉE",
      command: "03 · LE CENTRE DE COMMANDE",
      agents: "04 · LES AGENTS",
      orchestration: "05 · ORCHESTRATION",
      global: "06 · LE FUTUR",
      finale: "07 · L'INVITATION",
    },
    s1: {
      hint: "Le quotidien",
      cards: [
        "Email · 247 non lus",
        "Relance client",
        "Facture en retard",
        "Réunion dans 5 min",
        "Notion à jour",
        "Slack · 38 mentions",
        "RDV · jeudi 14h",
        "Tableau Excel à finir",
        "Prospects à relancer",
        "Rapport mensuel",
      ],
      pull: "Les entreprises perdent",
      strong: "des milliers d'heures",
      tail: "chaque année.",
    },
    s2: {
      eyebrow: "Et si…",
      title: "une intelligence pouvait travailler",
      title2: "à vos côtés 24h / 24 ?",
    },
    s3: {
      eyebrow: "Centre de commande",
      title: "Vous gardez la vision.",
      subtitle: "Vos agents exécutent.",
    },
    s4: {
      eyebrow: "Une équipe d'agents IA spécialisés",
      agents: [
        {
          name: "Prospection",
          mission: "Analyse, détecte, contacte, qualifie.",
          color: "#7dd3fc",
          kpi: { label: "Prospects qualifiés / mois", value: 1248 },
        },
        {
          name: "Marketing",
          mission: "Crée contenus, campagnes, publicités.",
          color: "#fbbf24",
          kpi: { label: "Posts générés / mois", value: 320 },
        },
        {
          name: "CRM",
          mission: "Classe, enrichit, suit, prévoit.",
          color: "#c084fc",
          kpi: { label: "Contacts orchestrés", value: 8540 },
        },
        {
          name: "Support",
          mission: "Répond 24 / 7, multilingue.",
          color: "#86efac",
          kpi: { label: "Messages traités / jour", value: 12400 },
        },
        {
          name: "Analyse",
          mission: "Observe, détecte, optimise, prévoit.",
          color: "#f0d27a",
          kpi: { label: "Anomalies détectées", value: 86 },
        },
      ],
    },
    s5: {
      eyebrow: "Orchestration",
      title: "Une équipe.",
      strong: "Sans limite.",
      sub: "Pendant que vous développez votre vision, vos agents exécutent.",
    },
    s6: {
      eyebrow: "Sur tous les continents",
      title: "Le réseau s'étend.",
      sub: "Europe · Amériques · Asie · Afrique · Moyen-Orient",
    },
    s7: {
      pre: "L'avenir n'est pas l'intelligence artificielle.",
      title: "L'avenir est la collaboration",
      title2: "entre l'humain et l'intelligence artificielle.",
      brand: "AMAVYA",
      subtitle: "Architectes d'agents intelligents.",
      cta: "Réserver une démo",
    },
  },
  en: {
    pageTitle: "AMAVYA — Vision 2035",
    pageDescription: "A cinematic journey into the future AMAVYA is building.",
    close: "Close",
    replay: "Replay",
    skip: "Skip",
    play: "Play",
    pause: "Pause",
    mute: "Mute",
    unmute: "Unmute",
    sceneLabels: {
      overwhelmed: "01 · OVERWHELMED",
      arrival: "02 · ARRIVAL",
      command: "03 · COMMAND",
      agents: "04 · THE AGENTS",
      orchestration: "05 · ORCHESTRATION",
      global: "06 · THE FUTURE",
      finale: "07 · THE INVITATION",
    },
    s1: {
      hint: "Daily reality",
      cards: [
        "Email · 247 unread",
        "Client follow-up",
        "Invoice overdue",
        "Meeting in 5 min",
        "Update Notion",
        "Slack · 38 mentions",
        "Call · Thursday 2pm",
        "Excel sheet to finish",
        "Leads to follow up",
        "Monthly report",
      ],
      pull: "Companies lose",
      strong: "thousands of hours",
      tail: "every year.",
    },
    s2: {
      eyebrow: "What if…",
      title: "an intelligence could work",
      title2: "by your side 24 / 7?",
    },
    s3: {
      eyebrow: "Command center",
      title: "You keep the vision.",
      subtitle: "Your agents execute.",
    },
    s4: {
      eyebrow: "A team of specialized AI agents",
      agents: [
        { name: "Prospecting", mission: "Analyzes, detects, contacts, qualifies.", color: "#7dd3fc", kpi: { label: "Qualified leads / month", value: 1248 } },
        { name: "Marketing", mission: "Creates content, campaigns, ads.", color: "#fbbf24", kpi: { label: "Posts generated / month", value: 320 } },
        { name: "CRM", mission: "Classifies, enriches, follows, predicts.", color: "#c084fc", kpi: { label: "Contacts orchestrated", value: 8540 } },
        { name: "Support", mission: "Answers 24 / 7, multilingual.", color: "#86efac", kpi: { label: "Messages handled / day", value: 12400 } },
        { name: "Analytics", mission: "Observes, detects, optimizes, forecasts.", color: "#f0d27a", kpi: { label: "Anomalies detected", value: 86 } },
      ],
    },
    s5: {
      eyebrow: "Orchestration",
      title: "One team.",
      strong: "No limits.",
      sub: "While you build the vision, your agents execute.",
    },
    s6: {
      eyebrow: "Across every continent",
      title: "The network grows.",
      sub: "Europe · Americas · Asia · Africa · Middle East",
    },
    s7: {
      pre: "The future is not artificial intelligence.",
      title: "The future is collaboration",
      title2: "between humans and artificial intelligence.",
      brand: "AMAVYA",
      subtitle: "Architects of intelligent agents.",
      cta: "Book a demo",
    },
  },
  es: {
    pageTitle: "AMAVYA — Visión 2035",
    pageDescription: "Un viaje cinematográfico al futuro que AMAVYA construye.",
    close: "Cerrar",
    replay: "Repetir",
    skip: "Saltar",
    play: "Reproducir",
    pause: "Pausa",
    mute: "Silenciar",
    unmute: "Activar sonido",
    sceneLabels: {
      overwhelmed: "01 · DESBORDADO",
      arrival: "02 · LA LLEGADA",
      command: "03 · CENTRO DE MANDO",
      agents: "04 · LOS AGENTES",
      orchestration: "05 · ORQUESTACIÓN",
      global: "06 · EL FUTURO",
      finale: "07 · LA INVITACIÓN",
    },
    s1: {
      hint: "Día a día",
      cards: [
        "Email · 247 sin leer",
        "Seguimiento cliente",
        "Factura vencida",
        "Reunión en 5 min",
        "Notion al día",
        "Slack · 38 menciones",
        "Cita · jueves 14h",
        "Excel por terminar",
        "Leads por contactar",
        "Reporte mensual",
      ],
      pull: "Las empresas pierden",
      strong: "miles de horas",
      tail: "cada año.",
    },
    s2: {
      eyebrow: "¿Y si…",
      title: "una inteligencia pudiera trabajar",
      title2: "a su lado 24 / 7?",
    },
    s3: {
      eyebrow: "Centro de mando",
      title: "Usted guarda la visión.",
      subtitle: "Sus agentes ejecutan.",
    },
    s4: {
      eyebrow: "Un equipo de agentes IA especializados",
      agents: [
        { name: "Prospección", mission: "Analiza, detecta, contacta, califica.", color: "#7dd3fc", kpi: { label: "Leads calificados / mes", value: 1248 } },
        { name: "Marketing", mission: "Crea contenidos, campañas, anuncios.", color: "#fbbf24", kpi: { label: "Posts generados / mes", value: 320 } },
        { name: "CRM", mission: "Clasifica, enriquece, sigue, predice.", color: "#c084fc", kpi: { label: "Contactos orquestados", value: 8540 } },
        { name: "Soporte", mission: "Responde 24 / 7, multilingüe.", color: "#86efac", kpi: { label: "Mensajes atendidos / día", value: 12400 } },
        { name: "Analítica", mission: "Observa, detecta, optimiza, prevé.", color: "#f0d27a", kpi: { label: "Anomalías detectadas", value: 86 } },
      ],
    },
    s5: {
      eyebrow: "Orquestación",
      title: "Un equipo.",
      strong: "Sin límite.",
      sub: "Mientras usted construye la visión, sus agentes ejecutan.",
    },
    s6: {
      eyebrow: "En todos los continentes",
      title: "La red se expande.",
      sub: "Europa · Américas · Asia · África · Oriente Medio",
    },
    s7: {
      pre: "El futuro no es la inteligencia artificial.",
      title: "El futuro es la colaboración",
      title2: "entre humanos e inteligencia artificial.",
      brand: "AMAVYA",
      subtitle: "Arquitectos de agentes inteligentes.",
      cta: "Reservar una demo",
    },
  },
};
